### ISSUE TITLE
Make YPP rewards customizable

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3479]
Make YPP rewards (actions):

- add rewards section to operator config:
```yaml
features:
  ypp:
    googleConsoleClientId: '$VITE_GOOGLE_CONSOLE_CLIENT_ID'
    rewards:
    - title: 'Upload video'
      description: 'Upload your video to Joystream'
      shortDescription: 'Upload your video to Joystream'
      baseAmount: 100 # Base amount that will be multiplied by tier multiplier
      actionButtonText: 'Go to My Videos'
      actionButtonPath: '/studio/videos' # Either this or `isRefer`
      isRefer: true # Either this or `actionButtonPath`
```
