### ISSUE TITLE
Idea: enhance user privacy

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#4272]
atlas makes a lot of requests to third-parties for [geolocation](https://github.com/Joystream/atlas/blob/master/docs/operator-guide.md#geolocation-service) and [analytics](https://github.com/Joystream/atlas/blob/master/docs/operator-guide.md#analytics).

Some operators may want to reduce those to enhance privacy. This is to improve documentation.

For testing following services are disabled like this:
```
analytics:
  assetLogs: # Asset logs are used to track distributors performance                                                                                                                                                                           
    url: '$VITE_ASSET_LOGS_URL'
  sentry: # Sentry can be used for capturing errors and logs from the app                                                                                                                                                                      
    dsn: null
  livesession: # Livesession can be used for user session recording                                                                                                                                                                            
    id: null
    rootHostname: '$VITE_LIVESESSION_ROOT_HOSTNAME'
  usersnap: # Usersnap can be used to capture user feedback                                                                                                                                                                                    
    id: null
```

Geolocation can be disabled at a price or replaced with an equivalent service by the operator.

Still there are 4 requests to assets on fonts.gstatic.com which can be self-hosted.
